### ISSUE TITLE
Trying to get ThingSpeak to work.

### ISSUE THREAD

**Issue by ronjtaylor** [fezfox/pool#1]
Hi, I am trying to get your https://www.fezfox.com/raspberry-pi-pool-temperature-monitor/ to work for me.
I have got as far as being able to bring up the Pool Temperature sensor on the FLASK web page but am stuck at getting the ThingSpeak to work.
In the documentation it tells me to 
"You need to first register at ThingSpeak. After you've created your account you will see a tab called "API keys" - place the "Write API key" and insert it into the config.py file."

I have never used ThingSpeak so I had to guess what I had to do next

1. Created an account
2. created a channel and found the write API Key

After about 2 hours nothing

I noticed these errors in the cronlog
Traceback (most recent call last):
  File "/home/pi/pool/poolmain.py", line 35, in <module>
    client.connect(broker_address, 1883, 60)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
 * Serving Flask app "poolweb" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

Can you point me in the right direction please?

Thank you

**Comment by Codepadawan** [comment]
Hi

Its been a couple of years since I tinkered with this, but you didn't
mention whether you inserted the key into the config.py file. Did you do
that?

https://github.com/fezfox/pool/blob/master/config.py

Line 31

Chris

**Comment by ronjtaylor** [comment]
Hi Chris,
Thanks for getting back to me.
Yes I did insert the key as per your instructions.

However since I posted the issue I have had some limited success. 
I decided just to e sure I did a sudo update and upgrade so that I was sure I had the latest code.  There was one module that was upgraded.
I then decided to try manually running 
pi@poolpizero:~ $ python3 /home/pi/pool/poolmain.py
and it worked!
**_Sent data to Thingspeak_** was reported on my terminal window.

This is my chart on Thingspeak
![image](https://user-images.githubusercontent.com/46874942/97369240-409e3c00-18f8-11eb-848e-8772228223da.png)

So it appears that things work from my terminal window but the crontab is bombin out when launcher.sh runs poolmain.py

The 2nd line in launcher.sh seems to be failing but the 3rd works because my web pages is working
cd /home/pi/pool
python3 /home/pi/pool/poolmain.py &
python3 /home/pi/pool/poolweb.py &

![image](https://user-images.githubusercontent.com/46874942/97369562-ea7dc880-18f8-11eb-8f05-1affe3ce2234.png)

I am thinking that it might be a permissions thing???
these are the permissions
-rw-r--r-- 1 pi pi  1011 Oct 27 14:49 config.py
-rw-r--r-- 1 pi pi  1024 Oct 27 14:55 config.py.save
-rwxr-xr-x 1 pi pi   192 Oct 27 12:09 launcher.sh
drwxr-xr-x 2 pi pi  4096 Oct 28 08:31 logs
-rw-r--r-- 1 pi pi  3790 Oct 27 12:09 poollib.py
-rw-r--r-- 1 pi pi  1552 Oct 27 12:09 poolmain.py
-rw-r--r-- 1 pi pi  2619 Oct 27 12:09 poolweb.py
drwxr-xr-x 2 pi pi  4096 Oct 27 14:57 __pycache__
-rw-r--r-- 1 pi pi 12706 Oct 27 12:09 README.md
drwxr-xr-x 2 pi pi  4096 Oct 27 12:09 static
drwxr-xr-x 2 pi pi  4096 Oct 27 12:09 templates
drwxr-xr-x 2 pi pi  4096 Oct 27 12:09 utils
Regards

**Comment by ronjtaylor** [comment]
Hi Chris,
After much head scratching and searching it dawned on my that the launcher script was running when environment variables were not yet set!!
So I introduced a small delay in the script.
I told it to sleep for 5 seconds

#!/bin/sh
# launcher.sh
# navigate to home directory, then to this directory, then execute python script
cd /home/pi/pool
sleep 5
python3 /home/pi/pool/poolmain.py &
python3 /home/pi/pool/poolweb.py &

That seems to have stopped the errors in the cronlog 
**_pi@poolpizero:~/pool/logs $ cat cronlog
 * Serving Flask app "poolweb" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off_**
my mosquitto seems to be running ok
**_pi@poolpizero:~ $ mosquitto_sub -v -t "pool/temperature"
pool/temperature 24.9
pool/temperature 24.9
pool/temperature 24.9
pool/temperature 25.1_**
I will now see if I can move onto getting it working in Home Assistant.
I run my HA on a i3NUC in docker on ubuntu 20.x

**Comment by Codepadawan** [comment]
Great to hear you got it working!
